- src/popover/Popover.js
> #2: remove semantic from popover (closes #2)

- examples/webpack.config.build.js
> #10: wooops (restore webbpack.build) (closes #10)

- package.json
- src/flex/FlexView.js
> #12: FlexView.grow should be either number or bool (closes #12)

- examples/components/Dropdown.js
- examples/examples.js
- examples/styles/dropdown-default.css
- package.json
> #18: update react-select (closes #18)

- examples/components/FlexView.js
- examples/examples.js
- package.json
- src/flex/FlexView.js
- src/flex/flexView.scss
> #17: [FlexView] about aligning things (closes #17)

- examples/components/LoadingSpinner.js
- examples/examples.js
- examples/index.html
- src/loading-spinner/LoadingSpinner.js
- src/loading-spinner/index.js
- src/loading-spinner/style.scss
> #21: add LoadingSpinner from LOL (closes #21)

- examples/components/Dropdown.js
- examples/components/FlexView.js
- examples/components/LoadingSpinner.js
- examples/components/Menu.js
- examples/components/Modal.js
- examples/components/Popover.js
- examples/examples.js
- src/cookie-banner/index.js
- src/dropdown/index.js
- src/index.js
> #24: package import is too verbose (closes #24)

- src/dropdown/Dropdown.js
- src/dropdown/DropdownMenu.js
- src/dropdown/index.js
> #27: fix confusion between "Dropdown" and "Select" (closes #27)

- examples/components/MobileDetector.js
- examples/examples.js
- package.json
- src/index.js
- src/mobile-detector/MobileDetector.js
- src/mobile-detector/index.js
> #31: add MobileDetector from oxway (closes #31)

- examples/components/LinkState.js
- examples/examples.js
- src/index.js
- src/link-state/index.js
> #29: add link state mixins and utility functions (closes #29)

- README.md
> lowercase buildo

- README.md
- src/flex/FlexView.js
- src/loading-spinner/LoadingSpinner.js
> #32: components should accept 'id' (closes #32)

- examples/components/Popover.js
- examples/example.css
- examples/examples.js
- examples/index.html
- src/popover/Popover.js
> #39: Add Popover from labonline (semantic free!) (closes #39)

- src/flex/FlexView.js
> #33: add "events" object prop and pass it to first child (closes #33)

- src/flex/FlexView.js
> #16: add shrink to FlexView (closes #16)

- src/flex/FlexView.js
> #46: remove basis=100% default when auto or shrink are set (closes #46)

- test/tests/exports.js
- test/tests/fake.js
> #43: add simple export tests (closes #43)

- package.json
> Node 4 compatibility

- npm-shrinkwrap.json
- package.json
> #55: Shrinkwrap (closes #55)

- package.json
> #57: Explicit react in peerDependencies (closes #57)

- examples/components/Popover.js
- src/popover/Popover.js
> #59: [Popover] margin offset should be customizable inline (closes #59)

- examples/components/Popover.js
- src/popover/Popover.js
> #62: [Popover] Improve positioning  (closes #62)

- examples/components/Popover.js
- src/popover/Popover.js
> #64: [Popover] - Statelessness (closes #64)

- examples/components/Popover.js
- examples/examples.js
- src/popover/Popover.js
> #63: [Popover] add dismissOnClickOut (closes #63)

- examples/components/Popover.js
- src/popover/Popover.js
> #71: Popover crashes if isOpen={true} from start (closes #71)

- src/popover/Popover.js
> #75: add state class to Popover (closes #75)

- package.json
- src/flex/flexView.scss
- src/scroll/ScrollView.js
> #81: better import of sass-flex-mixins (closes #81)

- package.json
- sass-importer.js
- src/flex/flexView.scss
> #83: custom sass importer to resolve ~ to node_modules/ (closes #83)

- examples/components/Toaster.js
- examples/example.css
- examples/examples.js
- examples/index.html
- src/index.js
- src/popover/Popover.js
- src/toaster/TimerToast.js
- src/toaster/ToastWrapper.js
- src/toaster/Toaster.js
- src/toaster/index.js
> #74: toaster (notifications manager) (closes #74)

- examples/webpack.config.build.js
- examples/webpack.config.js
- package.json
> #54: lodash should be a required dependency (not devDependency) (closes #54)

- src/flex/FlexView.js
- src/flex/flexView.scss
> #90: Add wrap prop to FlexView (closes #90)

- src/popover/Popover.js
> #86: [popover] fix children propType (closes #86)

- examples/components/BackgroundDimmer.js
- examples/examples.js
- src/background-dimmer/BackgroundDimmer.js
> #94: [Dimmer] implement background dimmer component (closes #94)

- examples/components/ModalManager.js
- examples/examples.js
- src/background-dimmer/BackgroundDimmer.js
- src/index.js
- src/modal-manager/ModalManager.js
- src/modal-manager/ModalWrapper.js
- src/modal-manager/index.js
> #87: [modal] implement modal manager (closes #87)

- src/toaster/Toaster.js
> #97: [Toaster] grained imports from react/addons (closes #97)

- src/background-dimmer/index.js
- src/index.js
> #98: [BackgroundDimmer] export directly from folders (closes #98)

- examples/components/TextOverflow.js
- src/text-overflow/TextOverflow.js
> #117: [TextOverflow] TextOverflow is too fragile and risky (closes #117)

- examples/components/Popover.js
- src/popover/Popover.js
> #112: [Popover] wrong positioning when hidden (closes #112)

- src/toaster/TimerToast.js
> #110: time(o|O)ut naming inconsistency (closes #110)

- src/transition-wrapper/TransitionWrapper.js
> #111: transitionStyles should be a required prop for Toaster (closes #111)

- examples/components/FlexView.js
- src/flex/FlexView.js
> #113: [FlexView] consistency between grow, shrink and flexBasis names (closes #113)

- src/flex/FlexView.js
Issue #124
**based on #123 commits**
> #124: [FlexView] shrink={false} doesn't work (closes #124)

- examples/components/ModalManager.js
- src/index.js
- src/modal-manager/BasicModal.js
- src/modal-manager/index.js
> #115: [modal] add basic Modal wrapper component (closes #115)

- src/modal-manager/BasicModal.js
- test/tests/exports.js
Issue #104
**BLOCKED BY #116**
> #104: [tests] update exports tests after last additions (closes #104)

- src/popover/Popover.js
> #127: [popover] Fix wrong positioning (again) (closes #127)

- src/modal-manager/ModalManager.js
> Allow to transfer context to modals (closes #130)

- src/modal-manager/ModalManager.js
> #140: [ModalManager] context wrapper breaks leave transition (closes #140)

- src/text-overflow/TextOverflow.js
> #145: [TextOverflow] fix #144 broken PR (closes #145)

- src/Panel/panel.scss
> #154: Remove non-direct css inheritance panel->panel-header' (closes #154)

- examples/components/button/default.example
- examples/components/index.js
- examples/examples.js
- src/button/Button.js
- src/button/ButtonLogic.js
- src/button/ButtonRenderer.js
- src/button/button.scss
- src/button/index.js
- src/index.js
> #157: Add `Button` from labonline (closes #157)

- .travis.yml
- README.md
> #162: use travis CI (closes #162)

- examples/components/index.js
- examples/components/more-or-less/default.example
- examples/examples.js
- examples/index.html
- src/index.js
- src/more-or-less/MoreOrLess.js
- src/more-or-less/index.js
- src/more-or-less/moreOrLess.scss
- test/tests/components/MoreOrLess.js
> #159: add `MoreOrLess` from labonline (closes #159)

- examples/components/confirmation-input/default.example
- examples/components/index.js
- examples/examples.js
- package.json
- src/confirmation-input/ConfirmationInput.js
- src/confirmation-input/confirmationInput.scss
- src/confirmation-input/index.js
- src/index.js
> #167: Add `ConfirmationInput` from Labonline (closes #167)

- src/button/Button.js
- src/button/ButtonRenderer.js
> #178: Button should accept custom TextOveflow (closes #178)

- src/flex/index.js
- src/link-state/index.js
- src/utils/log.js
Issue #182
imports on different projects shouldn't break (tested on LOL only)
> #182: Rewrite weird `export default { ... }`s (closes #182)

- examples/components/index.js
- examples/components/nav-bar/default.example
- examples/examples.js
- src/index.js
- src/nav-bar/NavBar.js
- src/nav-bar/index.js
> #175: Implement NavBar (closes #175)

- examples/components/index.js
- examples/components/toggle/default.example
- examples/examples.js
- src/index.js
- src/toggle/Toggle.js
- src/toggle/index.js
- src/toggle/toggle.scss
> #184: implement Toggle (closes #184)

- src/toaster/Toaster.js
> #134: [Toaster] div containers should be transparent to events (closes #134)

- src/badge/Badge.js
> #190: Badge shouldn't fill container (closes #190)

- examples/components/confirmation-input/default.example
- src/confirmation-input/ConfirmationInput.js
> #186: improve ConfirmationInput (closes #186)

- package.json
- src/confirmation-input/ConfirmationInput.js
> #194: update react-input-link to 0.0.5 (closes #194)

- src/toggle/toggle.scss
> #192: improve Toggle transition performance (closes #192)

- src/loading-spinner/LoadingSpinner.js
- src/text-overflow/TextOverflow.js
- src/toaster/Toaster.js
- src/utils/log.js
> #202: Safer way to get computed style of dom nodes, better warnings (closes #202)

- examples/components/BackgroundDimmer.example
- src/background-dimmer/BackgroundDimmer.js
Issue #196
**test plan**
examples work as expected (`onClickOutside` closes it, scroll propagation blocked)
tested on Labonline too -> it works with no errors nor warnings
> #196: improve BackgroundDimmer performance (closes #196)

- .eslintrc
- package.json
- src/Panel/Panel.js
- src/Panel/PanelMenu.js
- src/badge/index.js
- src/confirmation-input/ConfirmationInput.js
- src/nav-bar/index.js
- src/popover/Popover.js
- src/scroll/ScrollView.js
> #205: update buildo/eslint-config (closes #205)

- src/DropdownMenu/Menu.js
- src/DropdownMenu/dropdownMenu.scss
> #208: 'Menu should not have hover effect on disabled options' (closes #208)

- src/background-dimmer/BackgroundDimmer.js
- src/dropdown/Dropdown.js
- src/dropdown/DropdownMenu.js
- src/flex/FlexView.js
- src/loading-spinner/LoadingSpinner.js
- src/mobile-detector/MobileDetector.js
- src/modal-manager/BasicModal.js
- src/modal-manager/ModalManager.js
- src/popover/Popover.js
- src/scroll/ScrollView.js
- src/text-overflow/TextOverflow.js
- src/toaster/TimerToast.js
- src/toaster/Toaster.js
- src/transition-wrapper/TransitionWrapper.js
Issue #207
**test plan**
I used each component after refactoring it: no warnings nor crashes
> #207: use ES6 classes (closes #207)

- src/background-dimmer/BackgroundDimmer.js
- src/dropdown/DropdownMenu.js
- src/kitchen-sink/content/LiveDemo.js
- src/loading-spinner/LoadingSpinner.js
- src/popover/Popover.js
- src/scroll/ScrollView.js
- src/text-overflow/TextOverflow.js
- src/toggle/Toggle.js
> #215: use `React.findDOMNode` anywhere (closes #215)

- examples/components/index.js
- src/background-dimmer/BackgroundDimmer.js
- src/dropdown/Dropdown.js
- src/flex/FlexView.js
- src/loading-spinner/LoadingSpinner.js
- src/mobile-detector/MobileDetector.js
- src/modal-manager/BasicModal.js
- src/modal-manager/ModalManager.js
- src/popover/Popover.js
- src/scroll/ScrollView.js
- src/text-overflow/TextOverflow.js
- src/toaster/TimerToast.js
- src/toaster/Toaster.js
- src/transition-wrapper/TransitionWrapper.js
> #217: use @props + t-comb for prop evaluation (closes #217)

- src/flex/FlexView.js
> #222: Replace ReactNode with ReactChildren as children of FlexView (closes #222)

- package.json
> #224: Add react-remarkable (closes #224)

- examples/components/confirmation-input/default.example
- src/confirmation-input/ConfirmationInput.js
> #199: ConfirmationInput should have also onChange (closes #199)

- src/confirmation-input/ConfirmationInput.js
> #226: [ConfirmationInput] remove focus on `Enter` pressed (closes #226)

- src/DropdownMenu/dropdownMenu.scss
> #229: fix bug of margin affecting dropdownMenu and PanelMenu (closes #229)

- src/flex/flexView.scss
> #231: FlexView should set minHeight, minWidth to 0 by default (closes #231)

- src/scroll/ScrollView.js
> #237: use react event listeners in ScrollView (closes #237)

- src/button/ButtonRenderer.js
- src/button/button.scss
> #235: Fix button (closes #235)

- examples/components/scroll/ScrollTo.example
- src/scroll/ScrollView.js
Issue #239
-  Go on the example page [ScrollView](http://localhost:8080/#/componentId=ScrollView&sectionId=section-2 )
- Try to scroll down and you and will see buttons appear and disappear
- Try to scroll down with mobile touch event (using CDT) and you will see buttons appear and disappear
Note: onWheel as been commented because it have a wired side effect.
> #239: add ScrollView.onScroll prop (closes #239)

- examples/components/index.js
- examples/components/table/default.example
- package.json
- src/index.js
- src/table/README.md
- src/table/Table.js
- src/table/index.js
- src/table/patch-fixed-data-table.js
- src/table/table.scss
> #245: Add Table component (closes #245)

- src/DropdownMenu/Menu.js
- src/DropdownMenu/dropdownMenu.scss
- src/DropdownMenu/menu.scss
> #253: 'Style of Menu Component in its own file' (closes #253)

- src/popover/Popover.js
> #252: fix Popover render when attached to body (closes #252)

- examples/components/index.js
- examples/components/table/default.example
- src/table/Table.js
- src/table/table.scss
> #247: tableWrapper.scss should be easy to customize (closes #247)

- examples/components/table/default.example
- src/table/table.scss
> #261: remove arbitrary padding from Table header (closes #261)

- src/table/table.scss
> #263: Table should set background to cells instead of rows (closes #263)

- examples/components/toaster/Attached.example
- src/toaster/Toaster.js
> #79: [Toaster] add custom positioning (closes #79)

- src/scroll/ScrollView.js
> #240: ScrollView stop propagation should work also with visible scrollbars (closes #240)

- examples/components/Panel/docked.example
- src/Panel/Panel.js
> #250: Panel: defect on Safari (closes #250)

- src/table/Table.js
> #276: [Table] Suppress warnings due to footerDataGetter (closes #276)

- .travis.yml
- package.json
So that Travis catches linting issues
> Run lint before tests

- src/DropdownMenu/DropdownMenu.js
- src/Panel/Panel.js
- src/Panel/PanelHeader.js
- src/Panel/PanelMenu.js
- src/button/Button.js
- src/confirmation-input/ConfirmationInput.js
- src/flex/FlexCell.js
- src/meter/Meter.js
- src/panel-menu/PanelMenu.js
- src/panel-menu/components/Menu.js
- src/scroll/ScrollView.js
- src/table/Table.js
- src/text-overflow/TextOverflow.js
Issue #281
- run `npm run lint` and you will see no errors
NB: (there are still some errors but are not fixable, need more effort `React.createClass` into ES6 classes)
> #281: Lint errors fix (closes #281)

- src/Panel/panel.scss
> #287: [Panel] Panel Header should have overflow: hidden as default (closes #287)

- src/table/table.scss
> #289: Reset hover on table rows hover (closes #289)

- src/flex/FlexView.js
> #268: [FlexView] remove confusing `auto` prop (closes #268)

- src/flex/FlexCell.js
- src/panel-menu/PanelMenu.js
- src/panel-menu/components/Menu.js
Issue #291
No test plan is required for this, just check the code.
> #291: Add rules on lint disable comments (closes #291)

- src/flex/FlexView.js
> #270: [FlexView] drop support for `flexBasis` (closes #270)

- examples/components/flex/Column.example
- examples/components/flex/Row.example
- examples/components/flex/computeFlex.example
- examples/components/flex/index.js
- src/flex/FlexView.js
> #272: [FlexView] basis should always default to 'auto' even if grow={true} (closes #272)

- .eslintrc
- src/button/ButtonLogic.js
- test/tests/components/ButtonLogic.js
Issue #280
After discussion in #283 I ended up with @giogonzo solution.
The tests are almost useless now, so maybe we need to rethink about them (in a separate pr).
I also defined global `it` and `describe` in the `.eslintrc` for tests lint.
> #280: [Button] no check before invoke setState() for still mounted component (closes #280)

- test/tests/components/Meter.js
- test/tests/helpers/index.js
Issue #274
- run `npm test` and you will see them pass
> #274: [Meter] add unit test (closes #274)

- src/DropdownMenu/DropdownMenu.js
- src/Panel/PanelMenu.js
- src/badge/Badge.js
- src/button/ButtonRenderer.js
- src/more-or-less/MoreOrLess.js
> #301: [eslint] Resolve eslint errors due to recent rules update (closes #301)

- src/Panel/PanelHeader.js
- src/Panel/PanelMenu.js
- src/Panel/TabbedPanel.js
- src/Panel/panel.scss
> #296: [Panel] Panel should have shrink=false for all its children (closes #296)

- src/Panel/Panel.js
- src/Panel/PanelHeader.js
> #303: fix components using `FlexView` + `auto` (closes #303)

- src/table/Table.js
no changes in behavior, just for sanity https://facebook.github.io/react/docs/component-specs.html#updating-componentdidupdate
> newProps -> prevProps in componentDidUpdate

- examples/components/browser-detector/default.example
- examples/components/examples.json
- package.json
- src/browser-detector/BrowserDetector.js
- src/browser-detector/index.js
- src/index.js
> #316: implement BrowserDetector (closes #316)

- src/Icon/Icon.js
> #318: 'Add paths to icon with multipath' (closes #318)

- src/table/table.scss
> #321: not sortable columns should have header with cursor default (closes #321)

- examples/components/collapsable-section/default.example
- examples/components/examples.json
- src/accordion/index.js
- src/collapsable-section/CollapsableSection.js
- src/collapsable-section/collapsableSection.scss
- src/collapsable-section/index.js
- src/index.js
- src/kitchen-sink/sidebar/SidebarContent.js
- src/kitchen-sink/style.scss
> #308: [Accordion] rename in Section (closes #308)

- package.json
> #329: [Npm Task] Introduce a new test-dev task (closes #329)

- examples/components/background-dimmer/BackgroundDimmer.example
- src/background-dimmer/BackgroundDimmer.js
> #266: [BackgroundDimmer] (closes #266)

- package.json
Issue #331
CI should be happy again
> #331: temporarily pin eslint to 2.2.x (closes #331)

- examples/components/examples.json
- examples/components/time-picker/TimePicker12.example
- examples/components/time-picker/TimePicker24.example
- examples/components/time-picker/default.example
- src/index.js
- src/time-picker/README.md
- src/time-picker/TimePicker.js
- src/time-picker/index.js
- test/tests/components/TimePicker.js
> #277: TimePicker (closes #277)

- src/text-overflow/TextOverflow.js
> #107: [TextOverflow] Text ellipsis but no text ellipsis method called (closes #107)

- package.json
- src/DropdownMenu/Menu.js
- src/Icon/Icon.js
- src/Panel/Panel.js
- src/Panel/PanelMenu.js
- src/browser-detector/BrowserDetector.js
- src/button/Button.js
- src/confirmation-input/ConfirmationInput.js
- src/dropdown/Dropdown.js
- src/dropdown/DropdownMenu.js
- src/flex/FlexView.js
- src/kitchen-sink/KitchenSink.js
- src/link-state/index.js
- src/meter/Meter.js
- src/scroll/ScrollView.js
- src/table/Table.js
- src/time-picker/TimePicker.js
- src/transition-wrapper/TransitionWrapper.js
- test/tests/components/ButtonLogic.js
> #323: [dependencies] update lodash (closes #323)

- src/flex/FlexView.js
> #306: [FlexView]  if basis='auto' throw warning (closes #306)

- examples/components/examples.json
- examples/components/focusable-view/default.example
- examples/components/index.js
- src/focusable-view/FocusableView.js
- src/focusable-view/index.js
- src/index.js
> #265: FocusableView (closes #265)

- examples/components/styles.js
- src/dropdown/Dropdown.js
- src/dropdown/dropdown.scss
> #133: [Dropdown] export react-select style from /dropdown (closes #133)

- examples/components/text-overflow/WithFlexView.example
- src/text-overflow/TextOverflow.js
> #346: [TextOverflow] - treats not overflowed text as such (closes #346)

- examples/components/examples.json
- examples/components/popover/InitiallyOpen.example
- src/popover/Popover.js
> #334: Popover is not shown/open when `popover.isOpen` starts `true` (closes #334)

- src/text-overflow/TextOverflow.js
> #356: [TextOverflow] Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. (closes #356)

- src/dropdown/dropdown.scss
> #349: [Dropdown] Selected option reduce opacity (closes #349)

- src/Icon/Icon.js
> #364: [Icon] Add color prop (closes #364)

- src/background-dimmer/BackgroundDimmer.js
- `maxWidth` shouldn't be a **relative** value but **fixed**
- and `width` should be define as `maxWidth` was defined before
> Fix width and max-width for BackgroundDimmer

- package.json
- src/dropdown/Dropdown.js
- src/text-overflow/TextOverflow.js
- src/toaster/TimerToast.js
> #369: upgrade babel-eslint to 6.x.x (closes #369)

- src/DropdownMenu/DropdownMenu.js
- src/DropdownMenu/Menu.js
- src/Panel/Panel.js
- src/Panel/PanelHeader.js
- src/Tooltip/Tooltip.js
- src/background-dimmer/BackgroundDimmer.js
- src/button/Button.js
- src/focusable-view/FocusableView.js
- src/more-or-less/MoreOrLess.js
- src/nav-bar/NavBar.js
- src/popover/Popover.js
- src/scroll/ScrollView.js
- src/table/Table.js
- src/toaster/TimerToast.js
- src/toaster/Toaster.js
- src/transition-wrapper/TransitionWrapper.js
> #367: Replace t.ReactNode with t.ReactChildren (or t.ReactChild) (closes #367)

- src/dropdown/Dropdown.js
- src/dropdown/dropdown.scss
> #375: style Dropdown as described in the LOL guidelines (closes #375)

- src/dropdown/dropdown.scss
> #377: [dropdown] update placeholder colors as described in the guidelines (closes #377)

- examples/components/styles.js
- src/Tooltip/Tooltip.js
- src/Tooltip/tooltip.scss
- src/utils/index.js
> #379: update Tooltip to reflect new guidelines (closes #379)

- src/table/Table.js
Issue #381 
Copy-pasted the component in Ipercron and tested that the bug is not there anymore.
> #381: [Table] scrollToRow interacts poorly with autoSize (closes #381)

- examples/components/Panel/docked.example
- examples/components/Panel/tabbed.example
- src/Panel/Panel.js
- src/Panel/PanelHeader.js
- src/Panel/panel.scss
- src/Panel/panelMenu.scss
- src/Panel/tabbedPanel.scss
- src/badge/Badge.js
- src/more-or-less/moreOrLess.scss
> #371: overridable panel css (closes #371)

- src/collapsable-section/CollapsableSection.js
> #384: CollapsableSection should be a FlexView (support IE11) (closes #384)

- examples/components/dropdown/default.example
- src/dropdown/dropdown.scss
> #386: fix dropdown style (closes #386)

- .drone.yml
- .travis.yml
- package.json
> #383: Move to Drone CI (closes #383)

- src/button/Button.js
- src/button/ButtonLogic.js
- src/button/ButtonRenderer.js
- src/button/button.scss
- src/utils/index.js
- test/tests/components/ButtonLogic.js
> #387: [button] make it compatible with new style guidelines (closes #387)

- src/button/button.scss
> #392: Remove hover effect on disabled buttons (closes #392)

- src/button/button.scss
> #394: make circular button round (closes #394)

- src/button/button.scss
> #396: add variables for disabled button style (closes #396)

- package.json
this looks fine from LOL point of view, testing here: https://github.omnilab.our.buildo.io/buildo/aliniq/pull/2437
@FrancescoCioria do you see this as problematic for other projects?
> update versions of tcomb and revenge

- examples/examples.js
- package.json
- src/DropdownMenu/Menu.js
- src/background-dimmer/BackgroundDimmer.js
- src/dropdown/DropdownMenu.js
- src/kitchen-sink/content/LiveDemo.js
- src/loading-spinner/LoadingSpinner.js
- src/modal-manager/ModalManager.js
- src/popover/Popover.js
- src/scroll/ScrollView.js
- src/table/Table.js
- src/text-overflow/TextOverflow.js
- src/toaster/Toaster.js
- src/toggle/Toggle.js
- test/tests/components/ButtonLogic.js
> #244: react 0.14 compatibility (closes #244)

- src/toaster/Toaster.js
> #406: [toaster] fix React14 warning (closes #406)

- examples/components/DropdownMenu/deep.example
- examples/components/examples.json
- src/DropdownMenu/DropdownMenu.js
Issue #411
[![https://gyazo.com/5c87e89304404edd34d0fefbad4c0624](https://i.gyazo.com/5c87e89304404edd34d0fefbad4c0624.gif)](https://gyazo.com/5c87e89304404edd34d0fefbad4c0624)
> #411: [DropdownMenu] Make DropdownMenu's Menu inner component customizable (closes #411)

- src/DropdownMenu/menu.scss
That's why scrollbars appear on **AlinIQ** in `DropdownMenu`.
> DropdownMenu menu should have an auto overflow.

- src/DropdownMenu/Menu.js
- src/DropdownMenu/menu.scss
Issue #417
[![https://gyazo.com/3f890b3555998ccfe92f76697f12ba78](https://i.gyazo.com/3f890b3555998ccfe92f76697f12ba78.gif)](https://gyazo.com/3f890b3555998ccfe92f76697f12ba78)
> #417: [Menu] Menu item should render the title and metadata wrapped in a FlexView (closes #417)

- src/Panel/Panel.js
Issue #414
- tested on **AlinIQ** and it works like a charm.
- tested on Chrome (OSX)
- tested on Chrome (Windows)
- tested with IE11
> #414: [Panel] Panel content should be shrinkable (closes #414)

- src/more-or-less/MoreOrLess.js
> #420: [MoreOrLess] MoreOrLess should use flexbox to render its children properly (closes #420)

- src/button/button.scss
> #422: [Button] loader overlaps label (closes #422)

- src/button/button.scss
> #425: [button] it shouldn't have hover effect nor cursor pointer in processing state (closes #425)

- examples/components/Panel/docked.example
- examples/components/styles.js
- src/Panel/Panel.js
- src/Panel/PanelHeader.js
- src/Panel/panel.scss
> #433: [Panel] should be clickable anywhere in collapsed state (closes #433)

- examples/components/examples.json
- examples/components/resize-sensor/default.example
- examples/examples.js
- package.json
- src/index.js
- src/resize-sensor/ResizeSensor.js
- src/resize-sensor/index.js
Issue #445
[![https://gyazo.com/001b7792bd45e9a81d219689cc8ef770](https://i.gyazo.com/001b7792bd45e9a81d219689cc8ef770.gif)](https://gyazo.com/001b7792bd45e9a81d219689cc8ef770)
- Chrome50
- IE11
> #445: implement ResizeSensor component (closes #445)

- src/resize-sensor/ResizeSensor.js
Issue #447
- button + textoverflow example now works without errors
- tested on LOL too
I assumed a couple of things, read them in issue specs
> #447: [ResizeSensor] throws error on detach (closes #447)

- src/resize-sensor/ResizeSensor.js
> #451: [ResizeSensor] not isomorphic (closes #451)

- examples/components/examples.json
- examples/components/modal/default.example
- examples/components/modal/transition.scss
- examples/components/styles.js
- package.json
- src/index.js
- src/modal-manager/ModalManager.js
- src/modal/Modal.js
- src/modal/ModalPortal.js
- src/modal/index.js
- src/modal/modal.scss
- src/toaster/Toaster.js
- src/transition-wrapper/TransitionWrapper.js
Issue #432
tested with example:
[![https://gyazo.com/dd1cedb0e2941dfd9ec8be70999734f0](https://i.gyazo.com/dd1cedb0e2941dfd9ec8be70999734f0.gif)](https://gyazo.com/dd1cedb0e2941dfd9ec8be70999734f0)
IE11 too:
- modal works fine
- **bug: only scale transition is visible** (background opacity transition not working)
> #432: [Modal] Create a standalone Modal component (closes #432)

- .drone.yml
- package.json
- test/index.js
- test/tests/components/ButtonLogic.js
- test/tests/components/Meter.js
- test/tests/components/MoreOrLess.js
> #404: [tests] add tests back on CI (closes #404)

- test/tests/components/Dropdown.js
> #344: [Dropdown] Add Unit Test (closes #344)

- src/resize-sensor/ResizeSensor.js
Issue #456
- works like before
- fixed warning in LOL
> #456: [ResizeSensor] calling this.props.onResize when already unmounted (closes #456)

- src/confirmation-input/ConfirmationInput.js
- src/confirmation-input/confirmationInput.scss
- src/dropdown/dropdown.scss
> #459: Disabled state for confirmation input and dropdown (closes #459)

- src/Tooltip/tooltip.scss
Issue #464
tested in LOL:
- top/bottom distance is correct!
- arrow looks centered
> #464: Tooltip should keep into account border and arrow when positioning (closes #464)

- src/resize-sensor/ResizeSensor.js
- src/table/Table.js
Issue #466
[![https://gyazo.com/bee37aee7d86e83ed76550653ac497c4](https://i.gyazo.com/bee37aee7d86e83ed76550653ac497c4.gif)](https://gyazo.com/bee37aee7d86e83ed76550653ac497c4)
**tested on QIA too**
> #466: use ResizeSensor for Table autosize (closes #466)

- examples/components/meter/Meter.example
- examples/components/meter/MeterWithHole.example
- src/meter/Meter.js
- test/tests/components/Meter.js
> #472: [Meter] Range background color (closes #472)

- src/time-picker/TimePicker.js
Issue #478
[![https://gyazo.com/4090cc544229e5a327bf273046865a33](https://i.gyazo.com/4090cc544229e5a327bf273046865a33.gif)](https://gyazo.com/4090cc544229e5a327bf273046865a33)
> #478: [TimePicker] Make TimePicker searchable  (closes #478)

- src/time-picker/TimePicker.js
> #476: [Table] Make table scrollable  (closes #476)

- src/dropdown/dropdown.scss
> #482: Flat Dropdown should have border in normal state (closes #482)

- src/table/Table.js
> #476: [Table] Add scrollToColumn and scrollToRow props  (closes #476)

- src/Panel/panel.scss
> #484: Collapsed Panel content may overflow in IE (closes #484)

- src/button/Button.js
Issue #486
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}
> #486: Button should be clickable only when is ready (closes #486)

- src/button/Button.js
Issue #488
tested this branch on qia
> #488: [Button] children must be string, and code style (closes #488)

- src/table/table.scss
> #498: subtle change in ui behaviour of table scrollbars (closes #498)

- examples/components/styles.js
- src/Divider/Divider.js
- src/Divider/divider.scss
- src/DropdownMenu/DropdownMenu.js
- src/DropdownMenu/Menu.js
- src/DropdownMenu/menu.scss
- src/Panel/TabbedPanel.js
- src/Panel/tabbedPanel.scss
- src/collapsable-section/CollapsableSection.js
Issue #505
- `npm start`
- `examples look fine` ✅ 
> #505: Remove styles import (closes #505)

- src/Divider/Divider.js
- src/DropdownMenu/DropdownMenu.js
- src/Icon/Icon.js
- src/Panel/Panel.js
- src/Tooltip/Tooltip.js
- src/background-dimmer/BackgroundDimmer.js
- src/badge/Badge.js
- src/browser-detector/BrowserDetector.js
- src/button/Button.js
- src/collapsable-section/CollapsableSection.js
- src/confirmation-input/ConfirmationInput.js
- src/dropdown/Dropdown.js
- src/flex/FlexView.js
- src/focusable-view/FocusableView.js
- src/loading-spinner/LoadingSpinner.js
- src/meter/Meter.js
- src/mobile-detector/MobileDetector.js
- src/modal-manager/ModalManager.js
- src/modal/Modal.js
- src/more-or-less/MoreOrLess.js
- src/nav-bar/NavBar.js
- src/popover/Popover.js
- src/resize-sensor/ResizeSensor.js
- src/table/Table.js
- src/table/table.scss
- src/text-overflow/TextOverflow.js
- src/time-picker/TimePicker.js
- src/toaster/Toaster.js
- src/toggle/Toggle.js
- src/transition-wrapper/TransitionWrapper.js
Issue #491
ModalManager should keep working after the hack to fix @props decorator
- rebasing on #494 it should be possible to auto-generate every readme (except from FlexView that requires a folder renaming)
> #491: [KitchenSink] Props documentation (closes #491)

- .drone.yml
> #507: [KitchenSink] Add CI task to update doc-readmes  (closes #507)

- examples/components/dropdown/default.example
- src/dropdown/Dropdown.js
> #513: dropdown's menu's scrollbars hide menu when clicked in ie11 (closes #513)

- examples/components/ScrollView/ScrollView.example
- examples/components/examples.json
- examples/components/styles.js
- package.json
- src/ScrollView/ScrollView.js
- src/ScrollView/index.js
- src/ScrollView/scrollView.scss
- src/index.js
Issue #515
- added ScrollView (as it was, in other project)
- sass exposes style variables
- $scrollbarSize: 7px !default;
- $scrollbarSizeBig: 9px !default;
- $scrollbarColor: grey !default;
- $scrollbarContainerColor: white !default;
- added example
> #515: Add gemini ScrollView (closes #515)

- examples/components/examples.json
- scripts/template.js
- showroom/base.json
- showroom/components/App.js
- showroom/components/Component.js
- showroom/index.html
- src/kitchen-sink/KitchenSink.js
- src/kitchen-sink/content/Component.js
- src/kitchen-sink/content/LiveDemo.js
- src/kitchen-sink/sidebar/Sidebar.js
- src/kitchen-sink/sidebar/SidebarContent.js
- src/kitchen-sink/style.scss
- src/utils/theme/typography.scss
- src/utils/theme/variables.scss
> #519: [KitchenSink] Overall look&feel (closes #519)

- examples/components/examples.json
- src/kitchen-sink/style.scss
- src/utils/theme/variables.scss
> #523: [KitchenSink] Minor style changes (closes #523)

- src/table/table.scss
> #533: Add hover effect on table scrollbars, make them larger (closes #533)

- src/popover/Popover.js
> #462: add popover style prop (closes #462)

- src/Divider/divider.scss
- src/DropdownMenu/dropdownMenu.scss
- src/DropdownMenu/menu.scss
- src/Panel/panel.scss
- src/Panel/tabbedPanel.scss
- src/ScrollView/scrollView.scss
- src/Tooltip/tooltip.scss
- src/badge/badge.scss
- src/button/button.scss
- src/collapsable-section/collapsableSection.scss
- src/confirmation-input/confirmationInput.scss
- src/dropdown/dropdown.scss
- src/kitchen-sink/style.scss
- src/meter/meter.scss
- src/modal/modal.scss
- src/more-or-less/examples/default.scss
- src/more-or-less/moreOrLess.scss
- src/table/table.scss
- src/toggle/toggle.scss
- src/utils/theme/typography.scss
- src/utils/theme/variables.scss
Issue #535
Everything in Showroom should work as before
> #535: Avoid SASS variables collisions when override default style (closes #535)

- .drone.yml
Issue #547
should run on this PR
> #547: Run build-showroom check on PRs (closes #547)

- showroom/styles.js
- src/collapsable-section/examples/collapsableSection.scss
- src/collapsable-section/examples/default.js
> #553: [KitchenSink] CollapsableSection example restyling (closes #553)

- showroom/styles.js
- src/nav-bar/examples/default.js
- src/nav-bar/examples/navBar.scss
> #555: [KitchenSink] NavBar example restyling (closes #555)

- showroom/components.json
- showroom/styles.js
- src/badge/examples/icon.js
> #559: [KitchenSink] Add badge example (closes #559)

- package.json
- showroom/styles.js
- src/dropdown/Dropdown.js
- src/dropdown/dropdown.scss
- test/tests/components/Dropdown.js
> #517: Update react-select to v1.0.0-rc1 (closes #517)

- src/collapsable-section/examples/collapsableSection.scss
- src/collapsable-section/examples/default.js
> #563: [KitchenSink] CollapsableSection example style is overriding general style (closes #563)

- showroom/components.json
- showroom/styles.js
- src/dropdown/Dropdown.js
- src/dropdown/examples/dropdown.scss
- src/dropdown/examples/multi.js
- src/dropdown/examples/options.js
- src/dropdown/examples/sizes.js
> #557: [KitchenSink] Dropdown examples restyling (closes #557)

- package.json
- showroom/components.json
- showroom/components/Component.js
- showroom/components/Content.js
- showroom/components/useLocalReadmes.js
Finish removing remote loading of content.
> Finish removing remote loading

- src/DropdownMenu/Menu.js
- test/components/Menu.test.js
> #419: Menu: Menu is dismissed when user clicks on disabled menu item (closes #419)

- test/.eslintrc
> Replace ad-hoc eslint globals with jest env

- src/dropdown/Dropdown.js
Issue #604
- `npm start`
- `#/sections/components/component/time-picker?openSections=%3Bcomponents`
- try to change time
- it shouldn' break
> #604: Dropdown `onChange` prop should have `value` as argument (closes #604)

- showroom/styles.js
- src/browser-detector/examples/browserDetector.scss
- src/browser-detector/examples/default.js
- src/focusable-view/examples/default.js
- src/resize-sensor/examples/default.js
Issue #598
- BrowserDetector
- FocusableView
- ResizeSensor
> #598: [Examples restyling] various minor examples restyling (closes #598)

- src/dropdown/dropdown.scss
Issue #625
- change `$text-color-*` values
- every new value should work as expected
> #625: Dropdown: $text-color-* variables have no effect (closes #625)

- .drone.yml
Issue #619
Task executed in CI! ✔️
> #619: [Style Linter] Add CI step (closes #619)

- package.json
> accept any >= 3.6 < 4 eslint version

- showroom/components.json
- src/time-picker/examples/TimePicker12.js
- src/time-picker/examples/TimePicker24.js
> #637: Clean TimePicker examples (closes #637)

- package.json
- showroom/app.js
- showroom/components/app.scss
`npm start`
- UI looks ok
- normalize.css and boxSizing.css are bundled inside the style file
> Use buildo normalize css

- src/loading-spinner/LoadingSpinner.js
- src/loading-spinner/examples/LoadingSpinner.js
- test/components/LoadingSpinner.test.js
> Loading spinner tests

- src/button/StatefulButton.js
- test/components/StatefulButton.test.js
Issue #652
After have been updated `eslint-config` I run:
- `npm run lint`  => no errors ✔️
> #652: Add `eslint-plugin-promise` compatibility (closes #652)

- showroom/components.json
- showroom/styles.js
- src/input-children/examples/inputChildren.scss
> #657: New style for react-input-children examples (closes #657)

- showroom/component.index.html
- showroom/webpack.component.config.babel.js
Issue #672
- `npm start component` should render in a page without external css/js requests
> #672: [tablo perf] isolated index.html for isolated component (closes #672)

- showroom/components/App.js
Issue #678
`npm run lint` and CI passes
> #678: Fix eslint curly error (closes #678)

- src/tablo/examples/default.js
- src/tablo/tablo.scss
> #694: TextOverflow not working in tablo cells (closes #694)

- package.json
Closes #685
https://greenkeeper.io/
> chore(package): update stylefmt to version 5.0.3

- package.json
> chore(package): update babel-core to version 6.21.0

- package.json
> chore(package): update debug to version 2.4.5 (closes #698)

- package.json
> chore(package): update debug to version 2.5.1 (closes #709)

- src/dropdown/dropdown.scss
Issue #729
example setting `$arrow-color: red` and `placeholder-color: red`
> #729: Dropdown is ignoring scss variables (closes #729)

- src/dropdown/dropdown.scss
> #733: Dropdown: style for disabled options (closes #733)

- package.json
Closes #725
https://greenkeeper.io/
> chore(package): update smooth-release to version 7.0.0 (closes #725)

- src/Icon/Icon.js
- test/components/Icon.test.js
- test/components/__snapshots__/Icon.test.js.snap
> #686: Add tests to Icon (closes #686)

- src/tablo/Cell/Cell.js
- src/tablo/Column/Column.js
- src/tablo/examples/default.js
Issue #758
- updated examples as demo
> #758: Tablo: Cell children shoul take the entire row as second argument (closes #758)

- src/nav-bar/NavBar.js
- src/popover/Popover.js
- src/scroll/ScrollView.js
- src/transition-wrapper/TransitionWrapper.js
Hey there,
this PR was opened using [linto](https://github.com/buildo/linto).
Usually this means the shared ESLint config has been updated and these are the changes needed to comply with the new config.
The diff for this PR has been generated running `eslint --fix` using the updated ESLint config. Depending on the specific change, you may need to apply some manual fixes too.
Hope this helped!
Your friend,
linto 💄
> 💄  linto fix

- src/tablo/Cell/Cell.js
> #768: Tablo: Cell content should use grow, vAlignContent, hAlignContent (closes #768)

- src/tablo/Cell/Cell.js
- src/tablo/Cell/cell.scss
- src/tablo/Column/Column.js
- src/tablo/Header/Header.js
- src/tablo/Header/header.scss
- src/tablo/Tablo.js
- src/tablo/tablo.scss
- src/tablo/tabloVariables.scss
Issue #770
- tested on internal-project adding/redefining variables
- showroom works
> #770: Tablo: redefine variables for borders (closes #770)

- showroom/components.json
- src/dropdown/Dropdown.js
- src/dropdown/README.md
- src/dropdown/dropdown.scss
- src/dropdown/examples/menuOnTop.js
> #800: Dropdown: open the menu on top (closes #800)

- src/time-picker/README.md
- src/time-picker/TimePicker.js
> #802: TimePicker: add menuPosition prop (closes #802)

- src/dropdown/dropdown.scss
Closes #804
There should not be visible changes
> #804: Dropdonw: in multiselect mode, values should have height: 100% (closes #804)

- src/dropdown/dropdown.scss
Closes #810
* the new multi dropdown:
> #810: Dropdown: in multi mode, values should wrap and input height should adapt size (closes #810) 

- package.json
- showroom/webpack.config.build.babel.js
> Greenkeeper/stylelint webpack plugin 0.7.0

- src/dropdown/dropdown.scss
> #823: Dropdown: values in multi select mode are not aligned (closes #823)

- src/time-picker/TimePicker.js
- src/time-picker/examples/TimePicker24.js
Closes #825
* run the application, and check the 24H TimePicker, the value 11:23 should be selected.
825-timepicker_doesnt_update_the
* Open the dropdown menu, and see the option 11:23 within the options and in the right order
* retry by entering new value e.g. 08:33
* retry by enter the value 08:02 (value is not within the range)
* Change the state value of TimePicker12.js by: `state = { value: { hours: 11, minutes: 23 } }`
start typing 11:
> Should be compatible with every browser below. Check the ones you …
> #825: timePicker doesn't update the options with new input value (closes #825)

- src/dropdown/Dropdown.js
- src/dropdown/README.md
> #846: Define and export strict Dropdown's Props types (closes #846)

- src/dropdown/Dropdown.js
Closes #855
Tested on GDSM. It doesn't complain for additional props anymore
> #855: Dropdown: add supported props (closes #855)

- src/collapsable-section/collapsableSection.scss
> #857: CollapsableSection: cannot override $border-color (closes #857)

- src/tablo/Cell/Cell.js
> #867: Add contentStyle prop to tablo/Cell' (closes #867)

- showroom/components.json
- src/formatted-paragraph/FormattedParagraph.js
- src/formatted-paragraph/README.md
- src/formatted-paragraph/examples/default.js
- src/formatted-paragraph/index.js
- src/index.js
> #737: Implement FormattedParagraph (closes #737)

- src/Panel/TabbedPanel.js
- src/Panel/tabbedPanel.scss
Closes #875
- `TabbedPanel` still working as expected
> #875: TabbedPanel: fix tab layout (closes #875)

- package.json
> chore(package): update scriptoni to version 0.6.2

- package.json
> fix(package): update react-flexview to version 1.0.8

- package.json
> fix(package): update react-flexview to version 1.0.12

- package.json
Closes #943
- `.d.ts` files in the right `lib`'s subfolder ✅ 
> #943: [typescript .d.ts] Add npm task to copy file in lib (closes #943)

- src/badge/Badge.d.ts
- src/badge/index.d.ts
Closes #917
- tested on `alinity-pro` on `ts-brc` branch ✅ 
> #917: [typescript .d.ts] Badge (closes #917)

- src/text-overflow/TextOverflow.d.ts
- src/text-overflow/index.d.ts
> #937: [typescript .d.ts] TextOverflow (closes #937)

- src/button/Button.d.ts
- src/button/StatefulButton.d.ts
- src/button/index.d.ts
> #919: [typescript .d.ts] Button (closes #919)

- src/popover/Popover.d.ts
- src/popover/index.d.ts
> #933: [typescript .d.ts] Popover (closes #933)

- src/background-dimmer/BackgroundDimmer.d.ts
- src/background-dimmer/index.d.ts
- src/button/Button.d.ts
- src/button/StatefulButton.d.ts
- src/nav-bar/NavBar.d.ts
- src/nav-bar/index.d.ts
> #932: [typescript .d.ts] NavBar, Button, BackgroundDimmer (closes #932)

- src/toggle/Toggle.d.ts
- src/toggle/index.d.ts
> #940: [typescript .d.ts] Toggle (closes #940)

- package.json
- src/Panel/Panel.d.ts
- src/Panel/PanelHeader.d.ts
- src/Panel/TabbedPanel.d.ts
- src/async-status-indicator/AsyncStatusIndicator.d.ts
- src/async-status-indicator/index.d.ts
- src/background-dimmer/BackgroundDimmer.d.ts
- src/badge/Badge.d.ts
- src/browser-detector/BrowserDetector.d.ts
- src/browser-detector/index.d.ts
- src/button/Button.d.ts
- src/button/StatefulButton.d.ts
- src/collapsable-section/CollapsableSection.d.ts
- src/collapsable-section/index.d.ts
- src/confirmation-input/ConfirmationInput.d.ts
- src/confirmation-input/index.d.ts
- src/dropdown/Dropdown.d.ts
- src/dropdown/index.d.ts
- src/nav-bar/NavBar.d.ts
- src/popover/Popover.d.ts
- src/popover/index.d.ts
- src/text-overflow/TextOverflow.d.ts
- src/toggle/Toggle.d.ts
- src/toggle/index.d.ts
> #915: [typescript .d.ts] Async Status Indicator, BrowserDetector, CollapsableSection, ConfirmationInput and Dropdown (closes #915)

- src/ScrollView/ScrollView.d.ts
- src/ScrollView/index.d.ts
> #913: [typescript .d.ts] ScrollView (closes #913)

- src/async-status-indicator/AsyncStatusIndicator.d.ts
- src/async-status-indicator/index.d.ts
Closes #915
- tested on alinity-pro ✅ 
> #915: [typescript .d.ts] Async Status Indicator (closes #915)

- src/Panel/Panel.d.ts
- src/Panel/PanelHeader.d.ts
- src/Panel/TabbedPanel.d.ts
- src/Panel/index.d.ts
- src/Tooltip/Tooltip.d.ts
- src/Tooltip/index.d.ts
- src/button/Button.d.ts
- src/button/index.d.ts
- src/text-overflow/TextOverflow.d.ts
> #914: [typescript .d.ts] TextOverflow, Button, StatefulButton, Panel, PanelHeader, TabbedPanel and Tooltip (closes #914)

- src/Icon/Icon.d.ts
- src/Icon/index.d.ts
Closes #911
```js
import Icon from 'buildo-react-components/lib/icon';
import I, { IconProps, Props } from 'buildo-react-components/lib/icon/Icon';
```
No errors!
Also, tried some props -> correctly typed
> #911: [typescript .d.ts] Icon (closes #911)

- src/loading-spinner/LoadingSpinner.d.ts
- src/loading-spinner/index.d.ts
Closes #926
```js
import LoadingSpinner from 'buildo-react-components/lib/loading-spinner';
import L, { LoadingSpinnerProps, Props } from 'buildo-react-components/lib/loading-spinner/LoadingSpinner';
```
No errors!
> #926: [typescript .d.ts] LoadingSpinner (closes #926)

- package.json
- src/Divider/Divider.d.ts
- src/Divider/index.d.ts
- src/meter/Meter.d.ts
- src/meter/index.d.ts
- src/modal/Modal.d.ts
- src/modal/ModalPortal.d.ts
- src/modal/index.d.ts
- src/more-or-less/MoreOrLess.d.ts
- src/more-or-less/index.d.ts
- src/toaster/Toaster.d.ts
- src/toaster/index.d.ts
- src/transition-wrapper/TransitionWrapper.d.ts
- src/transition-wrapper/index.d.ts
> #939: [typescript .d.ts] Toaster, TransitionWrapper, MoreOrLess, Modal, Meter and Divider (closes #939)

- src/time-picker/TimePicker.d.ts
- src/time-picker/index.d.ts
Closes #938
```js
import TimePicker from 'buildo-react-components/lib/time-picker';
import T, { TimePickerProps, Props } from 'buildo-react-components/lib/time-picker/TimePicker';
```
No errors!
Also, tried some props -> correctly typed
> #938: [typescript .d.ts] Time Picker (closes #938)

- src/Tooltip/Tooltip.d.ts
Closes #914
- tested on alinity-pro ✅ 
> #914: [typescript .d.ts] Tooltip (closes #914)

- src/formatted-text/FormattedText.d.ts
- src/formatted-text/index.d.ts
> #924: [typescript .d.ts] FormattedText (closes #924)

- src/scroll/ScrollView.d.ts
- src/scroll/index.d.ts
Closes #935
- tested on `alinity-pro` ✅ 
> #935: [typescript .d.ts] Scroll (closes #935)

- src/mobile-detector/MobileDetector.d.ts
- src/mobile-detector/index.d.ts
> #928: [typescript .d.ts] MobileDetector (closes #928)

- src/modal-manager/BasicModal.d.ts
- src/modal-manager/ModalManager.d.ts
- src/modal-manager/index.d.ts
> #929: [typescript .d.ts] ModalManager (closes #929)

- src/tablo/plugins/columnsReorder/columnsReorderGrid.js
- src/tablo/plugins/columnsResize/columnsResizeGrid.js
- src/tablo/plugins/sortable/sortableGrid.js
> #980: Fix tablo (closes #980)

- src/resize-sensor/ResizeSensor.d.ts
- src/resize-sensor/index.d.ts
> #934: [typescript .d.ts] ResizeSensor (closes #934)

- src/DropdownMenu/DropdownMenu.d.ts
- src/DropdownMenu/Menu.d.ts
- src/DropdownMenu/index.d.ts
> #910: [typescript .d.ts] DropdownMenu (closes #910)

- showroom/components.json
- showroom/styles.js
- src/date-field/DateField.d.ts
- src/date-field/DateField.js
- src/date-field/README.md
- src/date-field/dateField.scss
- src/date-field/examples/default.js
- src/date-field/examples/isValid.js
- src/date-field/index.d.ts
- src/date-field/index.js
- src/index.js
Closes #219
tested with the two examples:
- user inputs is never overwritten by the new `props.value`
- validation seems to works
> #219: implement `DateInputs` (better name?) (closes #219)

- src/Panel/TabbedPanel.d.ts
- src/Panel/TabbedPanel.js
Closes #987
@FrancescoCioria it seems to work :) let me know if using basis as prop makes sense to you.
> #987: Update TabbedPanel (closes #987)

- src/Panel/tabbedPanel.scss
> #990: export $tab-border-height sass variables for tabbed panel (closes #990)

- src/popover/Popover.d.ts
- src/popover/Popover.js
- src/utils/index.js
Closes #993
- tested on alinity-pro ✅ 
> #993: Popover should handle context  (closes #993)

- showroom/components.json
- src/popover/Popover.d.ts
- src/popover/Popover.js
- src/popover/examples/hover-auto.js
- src/popover/examples/popover.scss
> Popover anchor auto

- src/button/StatefulButton.d.ts
> #1000: TypeScript: StatefulButton's `onClick` should always return a Promise (closes #1000)

- package.json
- src/Tooltip/TooltipTouch.d.ts
- src/Tooltip/TooltipTouch.js
- src/Tooltip/tooltipTouch.scss
- src/text-overflow/TextOverflowTouch.d.ts
- src/text-overflow/TextOverflowTouch.js
- src/text-overflow/textOverflowTouch.scss
Closes #901
- tested on *alinity-pro* ✅ 
> #901: backport mobile optimizations from alinity pro (closes #901)

- package.json
> fix(package): update @types/react to version 15.0.38

- src/Tooltip/Tooltip.d.ts
- src/Tooltip/Tooltip.js
Closes #1009
tested on AlinityPRO:
- no errors in console
- typescript is happy
This is how a string with three lines look:
> #1009: Tooltip: wrap text with FormattedText (closes #1009)

- src/TimePicker/README.md
- src/TimePicker/TimePicker.d.ts
- src/TimePicker/TimePicker.js
Closes #1016
tested manually in the showroom
> #1016: TimePicker should support `disabled` prop (closes #1016)

- src/Toggle/README.md
- src/Toggle/Toggle.d.ts
- src/Toggle/Toggle.js
- src/Toggle/toggle.scss
> #1021: add disabled prop to Toggle (closes #1021)

- showroom/components.json
- src/Popover/Popover.d.ts
- src/Popover/Popover.js
- src/Popover/examples/auto.js
Closes #1023
tested on AlinityPRO ->`Tooltip` is re-positioned correctly when there isn't enough space
> #1023: Popover: add logic to position it completely automatically (closes #1023)

- showroom/components.json
- src/Overflow/Overflow.d.ts
- src/Overflow/Overflow.js
- src/Overflow/README.md
- src/Overflow/examples/default.js
- src/Overflow/index.d.ts
- src/Overflow/index.js
- src/index.js
Closes #1025
tested a POC on AlinityPRO -> worked fine
tested with following example:
[![https://gyazo.com/159b1f888d8fbca32144f415761ae9e2](https://i.gyazo.com/159b1f888d8fbca32144f415761ae9e2.gif)](https://gyazo.com/159b1f888d8fbca32144f415761ae9e2)
> #1025: Implement `Overflow` (closes #1025)

- src/ScrollView/README.md
- src/ScrollView/ScrollView.d.ts
- src/ScrollView/ScrollView.js
> #1027: add innerComponent and innerComponentProps (closes #1027)

- showroom/components.json
- showroom/components/App.js
- src/Image/Image.js
- src/Image/README.md
- src/Image/examples/backgroundUrl.js
- src/Image/examples/image.js
- src/Image/getUrl.js
- src/Image/index.js
- src/index.js
> #1032: Image: copy-paste Image from buildo.io (closes #1032)

- src/Image/Image.js
> #1037: Image's props should not be strict (closes #1037)

- src/Icon/Icon.js
Closes #1042
tested on AlinityPRO:
> #1042: Icon: should pass fontSize directly to paths (closes #1042)

- test/components/Badge.test.tsx
My mistake, I missed the `.toBe(true)` part so those tests were not testing anything.
> Fix Badge tests (woops)

- src/BackgroundDimmer/BackgroundDimmer.tsx
- src/Button/Button.tsx
- src/CollapsibleSection/CollapsibleSection.tsx
- src/ConfirmationInput/ConfirmationInput.tsx
- src/Divider/Divider.tsx
- src/DropdownMenu/DropdownMenu.tsx
- src/Icon/Icon.tsx
- src/LoadingSpinner/LoadingSpinner.tsx
- src/Meter/Meter.tsx
> Make all TS components conform to #1082

- test/components/BackgroundDimmer.test.tsx
- test/components/Badge.test.tsx
- test/components/BrowserDetector.test.tsx
- test/components/CollapsibleSection.test.tsx
- test/components/Divider.test.tsx
- test/components/Dropdown.test.js
- test/components/Icon.test.tsx
- test/components/LoadingSpinner.test.tsx
- test/components/Menu.test.js
- test/components/Meter.test.tsx
- test/components/Modal.test.js
- test/components/MoreOrLess.test.js
- test/components/StatefulButton.test.tsx
- test/components/TimePicker.test.js
Closes #1081
I introduced a tcomb error (by making a prop non-optional) and some tests failed.
> #1081: Jest should fail on console.error (closes #1081)

- src/Button/StatefulButton.tsx
- test/components/StatefulButton.test.tsx
I must've missed this in the previous pass.
Tests still pass, it still works locally in the showroom.
> Make StatefulButton conform to #1082

- package.json
- src/TimePicker/TimePicker.d.ts
- src/TimePicker/TimePicker.js
> #644: TimePicker should allow to "localize" am/pm (closes #644)

- src/Dropdown/Dropdown.tsx
- src/TimePicker/TimePicker.tsx
- test/components/TimePicker.test.tsx
branch to be merged on master branch, (see [this](https://github.com/buildo/react-components/pull/1141) for the v0.27.x branch)
> #644bis: TimePicker should allow to "localize" am/pm (to master) 

- package.json
- src/MobileDetector/MobileDetector.tsx
Closes #1151
tested on a React 16 app (didn't test with react 16 as dev dep yet)
> #1151: Add support for React 16 (closes #1151)

- src/Dropdown/Dropdown.tsx
- src/Meter/Meter.tsx
> #1153: fix export to make react-styleguide happy (closes #1153)

- src/Panel/tabbedPanel.scss
- src/TimePicker/TimePicker.tsx
Closes #1155
examples still work fine
> #1155: Panel inside TabbedPanel has wrong style (closes #1155)

- src/FormattedText/FormattedText.tsx
> #1178: FormattedText detects some words as urls incorectly (closes #1178)

- src/Button/button.scss
> Add more variables to button scss

- src/Dropdown/dropdown.scss
> #1208: improve Dropdown sass variables (closes #1208)

- src/Dropdown/dropdown.scss
> #1214: dropdown has weird white line (closes #1214)

- src/Input/Input.tsx
- src/Input/input.scss
> #1216: Input border width and placeholder font weight should be overridable (closes #1216)

- src/Dropdown/dropdown.scss
> #1218: Dropdown: multi + small breaks the layout (closes #1218)

- src/Meter/Examples.md
- src/Meter/Meter.tsx
- src/Meter/meter.scss
- test/components/Meter.test.tsx
- test/components/__snapshots__/Meter.test.tsx.snap
> Improve Meter.tsx styleability (closes #1223)

- src/Dropdown/Dropdown.tsx
Closes #1230
- tested on Labeta
> #1230: Dropdown: Fix ref error when testing with Enzyme (closes #1230)

- src/Dropdown/Dropdown.tsx
- src/LoadingSpinner/LoadingSpinner.tsx
- src/Modal/BackgroundDimmer.tsx
- src/Overflow/Overflow.tsx
- src/Popover/Popover.tsx
- src/Scroll/ScrollView.tsx
- src/Tablo/plugins/autosize/autosizeGrid.tsx
- src/TextOverflow/TextOverflow.tsx
- src/Toggle/Toggle.tsx
- test/components/__snapshots__/LoadingSpinner.test.tsx.snap
Closes #1237
Tests are still 🍏 
Components are still working
> #1237: Update all string refs (closes #1237)

- src/Input/PasswordInput.tsx
Closes #1250
tested locally on a project 👍
> #1250: PasswordInput casuses a react warning (closes #1250)

- src/Divider/Divider.tsx
- test/components/Divider.test.tsx
> #1275: Divider: accept custom classnames (closes #1275)

- package.json
- src/Modal/ModalPortal.tsx
- src/Modal/modalWithContext.tsx
- src/Popover/Popover.tsx
- src/Scroll/ScrollView.tsx
- yarn.lock
Closes #1279
`test` and `build` pass
> #1279: build is broken with scoped type imports (closes #1279)

- src/Checkbox/Checkbox.tsx
- src/Checkbox/checkbox.scss
- src/FormField/CheckboxField.tsx
- src/FormField/Examples.md
- src/FormField/FormField.tsx
- src/FormField/ToggleField.tsx
- src/Toggle/Toggle.tsx
- src/Toggle/toggle.scss
- test/components/__snapshots__/Toggle.test.tsx.snap
> #1288: "focus" handling for Checkbox and Toggle (closes #1288)

- src/Checkbox/Checkbox.tsx
- src/Toggle/Toggle.tsx
> #1290: Checkbox and Toggle are missing tcomb props for onFocus, onBlur (closes #1290)

- src/FormField/FormField.tsx
> #1304: FormField style is broken (always rendered as horizontal) (closes #1304)

- src/FormField/formField.scss
> #1306: Horizontal FormField should not set flex-direction: row-reverse (closes #1306)

- src/FormField/DatePickerField.tsx
- src/FormField/DropdownField.tsx
- src/FormField/FormField.tsx
- src/FormField/InputField.tsx
- src/FormField/PasswordInputField.tsx
- src/FormField/TextareaField.tsx
- src/FormField/TimePickerField.tsx
- src/FormField/formField.scss
Closes #1308
** Required badge on left **
** Required badge on right **
> #1308: [FormField] Fix existing sass variables and add more customizable styling (closes #1308)

- src/Checkbox/Checkbox.tsx
> #1310: onClick is not prevented when the checkbox is disabled. (closes #1310)

- .gitignore
- ci/pipelines/test.yml
- ci/tasks/build-preview.sh
- ci/tasks/build-preview.yml
- ci/tasks/upload-preview.sh
- ci/tasks/upload-preview.yml
- package.json
> Adding preview to CI

- src/Dropdown/Dropdown.tsx
- src/FormField/DropdownField.tsx
> #1315: Fix export of Dropdown.Props (closes #1315)

- src/Popover/Popover.tsx
> #1313: stateless+attachToBody props make Popover crash on open (closes #1313)

- src/Dropdown/dropdown.scss
> #1323: Dropdown: border-color-hover variable has no effect (closes #1323)

- src/Dropdown/dropdown.scss
> #1322: Dropdown: when multi & searchable, remove single option button (x) should have cursor: pointer (closes #1322)

- src/Dropdown/Dropdown.tsx
Closes #1327
Both BRC and my current project compile 👍 without any change after this fix
> #1327: Dropdown doesn't type-check with some valid prop combinations (closes #1327)

- src/TimePicker/TimePicker.tsx
> #1331: expose size prop to Dropdown (closes #1331)

- src/Dropdown/dropdown.scss
> #1335: Dropdown is 2px higher when multi (closes #1335)

- src/Modal/modal.scss
> #1337: Modal header height is broken after upgrade of flexview (closes #1337)

- src/Form/Examples.md
- src/Form/Form.tsx
> #1344: Form with "submit on enter" behavior (closes #1344)

- src/Form/Examples.md
- src/Form/Form.tsx
Closes #1349
tested that both usage from TS and modified example work correctly
> #1349: Form defects and refinements (closes #1349)

- src/DatePicker/DatePicker.tsx
- src/FormField/CheckboxField.tsx
- src/FormField/DatePickerField.tsx
- src/FormField/DropdownField.tsx
- src/FormField/Examples.md
- src/FormField/FormField.tsx
- src/FormField/InputField.tsx
- src/FormField/PasswordInputField.tsx
- src/FormField/RadioGroupField.tsx
- src/FormField/TextareaField.tsx
- src/FormField/TimePickerField.tsx
- src/FormField/ToggleField.tsx
- src/FormField/formField.scss
- src/Textarea/textarea.scss
Closes #1321
**label**
**box**
**tooltip**
> #1321: FormField Hint (closes #1321)

- src/TimePicker/TimePicker.tsx
> #1352: expose components prop in TimePicker (closes #1352)

- src/TextOverflow/TextOverflow.tsx
Closes #1378
Tested that the component is now usable without type errors on an internal project
> #1378: typings regression on TextOverflow children/label props (closes #1378)

- src/Dropdown/commons.tsx
> #1384: Dropdown disabled not working (closes #1384)

- src/Toggle/Examples.md
> #1390: [Showroom] Toggle example is not working (closes #1390)

- src/Form/Form.tsx
Closes #1394
Tested locally in the showroom.
> #1393: noSubmitOnEnter in Form shall be optional  (closes #1394)

- src/EmptyPlaceholder/EmptyPlaceholder.tsx
> #1392: [Showroom] EmptyPlaceholder example not working (closes #1392)

- package.json
- yarn.lock
> #1397: [Tablo] Scrolling rows scrolls the underlying page too (closes #1397)

- src/Dropdown/Examples.md
- src/Dropdown/MultiDropdownWithSelectAll.tsx
- src/Dropdown/commons.tsx
- src/Dropdown/index.ts
- src/index.ts
- test/scripts/__snapshots__/build.test.ts.snap
> #947: Dropdown: SelectAll in multi mode (closes #947)

- src/Form/Examples.md
- src/index.ts
> #1395: [Showroom] Form example not working (closes #1395)

- src/EmptyPlaceholder/Examples.md
- src/index.ts
- styleguide/setup.ts
> #1401: Fix EmptyPlaceholder example (closes #1401)

- src/Form/Form.tsx
> #1403: The way Form passes props down to the View causes React warnings (closes #1403)

- src/TextOverflow/TextOverflow.tsx
> #1407: Fix return type for TextOverflow's render method (closes #1407)

- package.json
- yarn.lock
> #1424: update react-input-children version (closes #1424)

- package.json
- src/DatePicker/DatePicker.tsx
- src/FormField/DatePickerField.tsx
- yarn.lock
Closes #1423
if `isClearable={false}` or not defined
- `value` has to be defined and it can't be `null`
- if defined, `onChange` has to be `(date: LocalDate) => void`
- there is no _clear_ icon
if `isClearable={true}`
- `value` has to be defined, but can be `null`
- if defined, `onChange` has to be `(date: LocalDate | null) => void`
- there is a _clear_ icon
----------
⚠️  **this is a breaking change** since the component was clearable by default and `value` was optional, now it's not clearable by default and `value` is always mandatory
> #1423: DatePicker should have clearable option (closes #1423)

- src/Form/Examples.md
- src/FormField/Examples.md
Closes #1432
`yarn start` and verified that no example is broken
> #1432: Showroom examples for InputField is broken (closes #1432)

- src/DatePicker/datePicker.scss
This pr fix DatePicker component not working with yarn 2 or yarn workspaces
> fix(DatePicker): broken with yarn 2 or yarn workspaces

- package.json
This pr update the post install script to not give an error when in installed with yarn 2
> Update postinstall script

- src/DatePicker/datePicker.scss
> Fix compile issue on yarn 1

- src/DatePicker/datePicker.scss
- src/FormField/RadioGroupField.tsx
- src/RadioGroup/Examples.md
- src/RadioGroup/RadioGroup.tsx
> 1476 radio group doesnt support custom values
