buildo/react-components

src/loading-spinner/LoadingSpinner.js

`LoadingSpinner` shouldn't have a default color, so that it's able to inherit from container

Remove default color of LoadingSpinner

---

examples/components/Popover.js
src/popover/Popover.js

#49: [Popover] rename misleading type props "absolute" and "relative" (closes #49)

---

src/modal-manager/ModalManager.js

React threats `undefined` and `false` children differently: `children = []` and `children = [<noscript />]` respectively
This should prevent issues when rendering `<ModalManager>{false}</ModalManager>`

safer ModalManager children.map

---

src/text-overflow/TextOverflow.js

Issue #143
The `setTimeout` seemed useless and it was the cause of some exceptions when the component was forced to render.
Consider `setTimeout()` with no delay put its callback in the next execution queue, the forced rendered `TextOverflow` threw exception if the component has unmounted in the meantime.
The attachment shows the lifecycle of `TextOverflow` components.

#143: [TextOverflow] verify if setTimeout is needed (closes #143)

---

src/more-or-less/MoreOrLess.js
src/more-or-less/moreOrLess.scss

#168: center expand button in MoreOrLess (closes #168)

---

src/loading-spinner/LoadingSpinner.js

Issue #200
- `LoadingSpinner` should not log warnings anymore if its container has `position: absolute`

#200: LoadingSpinner container being position absolute is ok (closes #200)

---

src/Panel/panel.scss

#220: remove old margin-top to .expand-icon in panel.scss' (closes #220)

---

src/table/Table.js
src/table/table.scss

Issue #256
- in LOL the keyboard shortcuts should work as usual
- **NB**: do not remove `tabIndex` prop or `Shortcut` would stop to work

#256: Remove keypress listener and handlers from Table (closes #256)

---

src/flex/FlexView.js

Issue #305 
**test plan**
- `<FlexVIew basis="200" />` -> `flex: 0 0 200px`
- `<FlexVIew basis="200a" />` -> `flex: 0 0 200a`

#305: [FlexView] basis should append 'px' also to string numbers (closes #305)

---

src/Panel/Panel.js

Issue #311
- `Panel` should accept `ReactChildren` children

#311: 'Panel schould accept ReactChildren as Children' (closes #311)

---

src/background-dimmer/BackgroundDimmer.js

Issue #351
- if content is higher/wider than 90% of window it correctly scrolls! (if `children` has `overflow: scroll` of course :dancer: )

#351: [background-dimmer] content should scroll when too big (closes #351)

---

src/table/Table.js

Issue #358
- tested on `LOL` and it works
- i was able to set column width on `onColumnResizeEndCallback` invocation
- i was able to hide black vertical line by passing `isColumnResizing = false` on `onColumnResizeEndCallback` call.

#358: [Table] Add prop to handle column resize (closes #358)

---

examples/components/Panel/tabbed.example
src/Panel/TabbedPanel.js

Issue #360
- Open examples page
- Click on `Panel`
- The 3rd example will show you the expected behaviour
Note: if very very long, is not managed. It will be a very uncommon behaviour IMO, to me we can leave it free and make it editable by the user (with `overflow:hidden` or `text-overflow: ellipsis` for instance) 
cc @FrancescoCioria

#360: [TabbedPanel] tabs should have same width (closes #360)

---

src/dropdown/Dropdown.js

#398: '[Dropdown] backspaceRemoves should default to clearable' (closes #398)

---

src/DropdownMenu/Menu.js

Issue #409
`npm run test` failed due to a wrong import (not related to this pr).

#409: [DropdownMenu] Menu item is not really vertical centered (closes #409)

---

src/Tooltip/Tooltip.js

Issue #427
tested on associated LOL pr: nothing breaks
- not applicable
- not applicable
- unfortunately missing :(
everything else

#427: [Tooltip] fix Tooltip.popover prop typing (closes #427)

---

src/badge/Badge.js

Issue #439
- it should accept a ReactChildren as label

#439: Badge label should be react children (closes #439)

---

examples/components/examples.json
examples/components/text-overflow/Resizable.example
src/text-overflow/TextOverflow.js

Issue #436
[![https://gyazo.com/865b67f71e952420b4b6c9e901f8ad1a](https://i.gyazo.com/865b67f71e952420b4b6c9e901f8ad1a.gif)](https://gyazo.com/865b67f71e952420b4b6c9e901f8ad1a)
I didn't directly tested it on IE11 but the only browser-dependent logic is in `ResizeSensor` which works on IE11

#436: [TextOverflow] Should update also on parent resize (closes #436)

---

src/text-overflow/TextOverflow.js

Issue #449
- verified that old bug ( #346 ) is still here (checkout at 265-focusableview which is last PR for #346):
[![https://gyazo.com/a56c2ee3a4c4e14b82890b3ee1d37160](https://i.gyazo.com/a56c2ee3a4c4e14b82890b3ee1d37160.gif)](https://gyazo.com/a56c2ee3a4c4e14b82890b3ee1d37160)
- remove `setTimeouts`
- no visible bug:
[![https://gyazo.com/9fb91853f3f145c68c060bd93200ac0f](https://i.gyazo.com/9fb91853f3f145c68c060bd93200ac0f.gif)](https://gyazo.com/9fb91853f3f145c68c060bd93200ac0f)
- log forced `verifyOverflow`s
- it's called twice (first and third example were the one with the bug visible)
tested on IE11 too

#449: [TextOverflow] remove setTimeouts (closes #449)

---

src/toggle/Toggle.js

`value` and `onChange` props were not considered
didn't test the valueLink version yet

fix stateless toggle

---

examples/components/index.js
examples/components/text-overflow/Default.example
src/text-overflow/TextOverflow.js

Issue #468
- tested every example with both `lazy: true` and `lazy: false` -> everything worked as expected
- tested on QIA -> ✅ 
- tested on AMS -> ✅ 

#468: make TextOverflow optionally lazy (closes #468)

---

examples/components/text-overflow/Default.example
src/text-overflow/TextOverflow.js

Issue #470
[![https://gyazo.com/23513d71544a9aa9ed51be6945c3e605](https://i.gyazo.com/23513d71544a9aa9ed51be6945c3e605.gif)](https://gyazo.com/23513d71544a9aa9ed51be6945c3e605)
PS: tested on QIA too --> the defect (tooltip remaining open) has gone 🎉 

#470: Add optional delay to TextOverflow (closes #470)

---

examples/components/Tooltip/long-word.example
examples/components/examples.json
src/Tooltip/tooltip.scss

#473: [Tooltip] Tooltip doesn't wrap long words (closes #473)

---

package.json
scripts/generateReadmes.js
scripts/parse.js
scripts/template.js
src/Divider/Divider.js
src/DropdownMenu/DropdownMenu.js
src/Panel/Panel.js
src/Tooltip/Tooltip.js
src/dropdown/Dropdown.js
src/kitchen-sink/KitchenSink.js
src/kitchen-sink/content/Component.js
src/kitchen-sink/content/Content.js
src/kitchen-sink/content/ExampleCard.js
src/kitchen-sink/content/LiveDemo.js
src/kitchen-sink/sidebar/Item.js
src/kitchen-sink/sidebar/Sidebar.js
src/kitchen-sink/sidebar/SidebarContent.js
src/table/Table.js
src/time-picker/TimePicker.js
src/toaster/Toaster.js

Issue #494
I created a new version of `generateReadme.js` file following the approach given by `tcomb-react` to extract component documentation.
The script is testable by:
```shell
$ npm run generate-all-readmes 
```
The npm task doesn't work as it is cause the components don't have the correct documentation structure to be parsed, cause I've defined strict rules in order to be sure every component is documented rightly, and the rules are:
- component must have a name (now it's extracted from the the class name)
- component must have a description (even a simple one, but it's required from my pov)
- each component props must be documented
You can add comments 
```js
/**
* Component description here
* @param prop1 - this is the prop 1 description 
* @param prop2 - this is the prop 2 …
```

#494: [KitchenSink] Readme generator (closes #494)

---

src/table/table.scss

Issue #509
- added `scrollbar-size` sass variable in `table.scss`
- not breaking, using the var is optional and falls back to the default scrollbar's size

#509: add table's scrollbars customization (closes #509)

---

scripts/template.js

Issue #538
`overlay` default value in `Modal` README doesn't break the layout anymore

#538: Broken props table in READMEs (closes #538)

---

package.json
test/.eslintrc
test/components/BackgroundDimmer.test.js
test/components/Badge.test.js
test/components/BrowserDetector.test.js
test/components/Divider.test.js
test/components/Dropdown.test.js
test/components/Meter.test.js
test/components/MoreOrLess.test.js
test/components/StatefulButton.test.js
test/components/TimePicker.test.js
test/components/__snapshots__/BackgroundDimmer.test.js.snap
test/components/__snapshots__/Badge.test.js.snap
test/components/__snapshots__/Divider.test.js.snap
test/components/__snapshots__/Dropdown.test.js.snap
test/components/__snapshots__/Meter.test.js.snap
test/components/__snapshots__/MoreOrLess.test.js.snap
test/components/__snapshots__/StatefulButton.test.js.snap
test/components/__snapshots__/TimePicker.test.js.snap
test/render.js

Now that we switched to react 15, we can finally use `react-test-renderer`.
Also, we can finally experience [this bug](https://github.com/facebook/react/issues/7386) which forced me to ignore 4 tests. It should be fixed in the upcoming react 15.4  release

Use react-test-renderer

---

.npmignore

Issue #608
- it should be installable now (try `npm ${LOCAL_FORLDER}`)

#608: Remove dot sh from npm ignore (closes #608)

---

src/kitchen-sink/sidebar/SidebarContent.js
src/popover/Popover.js
src/popover/examples/hover.js

Issue #605
- pass `delay: undefined`
- opens immediately
- closes immediately
- debounced event cb is not called (calling directly `_onMouseEvent`)
- pass `delay: 1000`
- opens after 1s
- closes after 1s
- pass `delay: { whenOpen: 100 }` (that I left as new default in the hover example)
- opens immediately
- closes after 100ms (enough to move the cursor to the popover before it closes)

#605: Popover: support delay on mouse events (closes #605)

---

src/dropdown/dropdown.scss

Issue #623
- try to change `menu-background` variable to `red` or anything
- `npm start && open http://localhost:8080http://localhost:8080/#/sections/components/component/dropdown?`
- menu should be `red` (or anything)

#623: Dropdown: menu-background should be applied also to option (closes #623)

---

src/time-picker/TimePicker.js
test/components/BackgroundDimmer.test.js
test/components/Badge.test.js
test/components/Dropdown.test.js
test/components/Meter.test.js
test/components/MoreOrLess.test.js
test/components/StatefulButton.test.js
test/components/TimePicker.test.js
test/components/__snapshots__/BackgroundDimmer.test.js.snap

Issue #612
- Time picker options are computed correctly and refreshed whenever input changes
- Can navigate through options with arrow keys ✅ 
[![https://gyazo.com/7250d349efab16bc86a488990a4500dc](https://i.gyazo.com/7250d349efab16bc86a488990a4500dc.gif)](https://gyazo.com/7250d349efab16bc86a488990a4500dc)

#612: TimePicker selection, keyboard selection and focus (closes #612)

---

src/dropdown/dropdown.scss

Issue #635
- set `option-background-selected` to "green"
- set `option-color-selected`  "red"
-->
[![https://gyazo.com/b61cf1b470971dfa28bef31b3bc56420](https://i.gyazo.com/b61cf1b470971dfa28bef31b3bc56420.gif)](https://gyazo.com/b61cf1b470971dfa28bef31b3bc56420)
PS: I also tested that option-background-hover still works:
- set `$option-background-hover` to "black"
- option turns black when hovered

#635: Dropdown: add sass variable $option-background-selected (closes #635)

---

src/focusable-view/FocusableView.js

Issue #455
`debounce: undefined` --> no debounce
`debounce: 1000` --> focus/blur events are merged and debounced of 1000ms
- rapidly focus/blur/focus/blur --> onFocus/onBlur never called --> no rerender even without `@pure`

#455: [FocusableView] optionally debounce focus/blur events (closes #455)

---

src/loading-spinner/loadingSpinner.scss

Issue #649
- ui shouldn't break in project without buildo/normalize (i.e. global `box-sizing: border-box`)

#649: LoadingSpinner should enforce box-sizing: border-box (closes #649)

---

src/time-picker/TimePicker.js
test/components/TimePicker.test.js

Issue #663
Start the react-component application
go to [http://localhost:8080/#/sections/components/component/time-picker](url)
select one of the options from the drop-down menu of the time-picker (either 12H or 24H format)
inspect the option of the selected time (to keep the menu opened while the devtool is opened click `cmd+F8+\`) 
The option should have the "is-selected" class
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

#663: TimePicker missing "is-selected" class (closes #663)

---

.gitignore
npm-start.sh
package.json
showroom/app.component.js
showroom/components/IsolatedComponentView/index.js
showroom/webpack.component.config.babel.js

Issue #667
- `npm start component`
- it creates the default `Component.js` file
- pointing to `localhost:8080` => it renders a message that invites you to edit the `Component.js` file
- Edit `Component.js` and paste the content of [this](https://gist.github.com/veej/a4928a7e24e65e7e3e0e89ca293376d8) gist => isolated `Tablo` example!! YAY!!!!
- `npm start` still working as before

#667: [tablo perf] Create an isolated environment for testing (closes #667)

---

src/tablo/plugins/selectable/selectableGrid.js

Issue #682
- not passing `selectionType` to `Tablo` shouldn't raise warnings/errors in the console. The internal logic would set it to `none`

#682: SelectionType should be optional (closes #682)

---

src/tablo/Tablo.js

Issue #680
- export `Tablo` as is, without decorators (if you do, `sortable` will add `children` for you and the assert will pass anyway)
- use it without `children`
- you shouldn't get errors in the console

#680: Fix Tablo assert on children (closes #680)

---

package.json

Reverts buildo/react-components#677
Sorry @greenkeeperio-bot but I don't trust `react-select@1.0.0-rc2` as:
- it's not officially published
- there's not release on its repo
- there's not changelog but it has [106 freaking new commits](https://github.com/JedWatson/react-select/compare/v1.0.0-rc.1...master) compared to `react-select@1.0.0-rc1`

Revert "Update dependencies to enable Greenkeeper 🌴"

---

src/popover/Popover.js

Issue #701
- warning is no longer there :)
- pass `delay={{ whenOpen: 100, ciao: true }}`
~~- tcomb complains (`interface` is indeed `strict`)~~
~~PS: We were using `t.interface` only in `Modal`:~~
~~Also in this case it's correct to make it `strict`~~

#701: Popover: delay prop validation always fails if you pass an object (closes #701)

---

src/tablo/API.md
src/tablo/Column/Column.js

Issue #713
- log `allowCellsRecycling` prop
- `allowCellsRecycling` is `true` by default
- explicitly pass `allowCellsRecycling={false}`
- `allowCellsRecycling` is `false`

#713: [Tablo Perf] horizontal virtualization should be settable and on by default (closes #713)

---

src/tablo/API.md
src/tablo/examples/default.js
src/tablo/plugins/selectable/selectableGrid.js
src/tablo/plugins/selectable/selectableGrid.scss
src/tablo/tablo.scss
src/tablo/tabloVariables.scss

Issue #714
- hover a row in `default` example
- row background is colored correctly
- select a row and hover it
- row background is set to the hover one (hover beats select)
- pass `onRowMouseEnter` and `onRowMouseLeave` to `Tablo`
- correctly called when entering/leaving a row

#714: [Tablo Perf] handle hover style for rows in CSS (closes #714)

---

src/Panel/Panel.js
src/Panel/PanelHeader.js

Issue #721
- if size is not specified, or `size='small'`, header height is 48px
- adding size = `medium`, header height is 56px
- adding `size='small'`, header height is 40px

#721: Panel: header height should be configurable (closes #721)

---

showroom/components.json
src/modal/Modal.js
src/modal/examples/noFooter.js
src/modal/examples/noHeader.js

Issue #671
Added 2 examples for test purpose:
- modal with no header
- modal with no footer
Shouldn't this be breaking?

#671: Modal renders header/footer even when not necessary (closes #671)

---

src/dropdown/Dropdown.js

Issue #731
Tested passing a `onValueClick` function that focus the input after erasing the selected value:

#731: Dropdown: expose focus function (closes #731)

---

src/tablo/API.md
src/tablo/Tablo.js
src/tablo/examples/default.js
src/tablo/plugins/selectable/selectableGrid.js

Issue #741
tested in the examples
- especially the screenshot shows that the both the `selected` class is added and both the one returned by `rowClassNameGetter(index)`

#741: Tablo: expose `rowClassNameGetter` (closes #741)

---

src/tablo/plugins/sortable/Arrow.js

#750: Tablo: in IE11 sort icons are misaligned (closes #750)

---

src/tablo/plugins/columnsReorder/DNDHeader.js
src/tablo/plugins/columnsReorder/columnsReorderGrid.scss
src/tablo/plugins/sortable/sortableGrid.scss
src/tablo/tabloVariables.scss

Issue #755
- `sortableGrid`: nothing should be changed, as the default values of the sass variables are the same used before in the source code
-  `columnsReorder`: there's no more a drag icon, the header is entirely draggable

#755: Tablo: ui changes (closes #755)

---

src/tablo/tablo.scss
src/tablo/tabloVariables.scss

Issue #760
Settings the variables properly, now devs can do this
[![https://gyazo.com/ed6da6c61fc7e0bed8535531c3c514d9](https://i.gyazo.com/ed6da6c61fc7e0bed8535531c3c514d9.gif)](https://gyazo.com/ed6da6c61fc7e0bed8535531c3c514d9)

#760: Tablo: background on hover should have different variables for even and odd rows (closes #760)

---

src/tablo/Cell/Cell.js

Issue #762
`Cell`
- should grow by default
- should be overridable

#762: Tablo: `Cell` should grow (closes #762)

---

src/badge/badge.scss

Issue #771
PS: it was working also before as in the showroom `flexView.css` is bundled after `badge.scss`

#771: Badge is overriding FlexVIew's `display` property (closes #771)

---

src/popover/Popover.js

Issue #727
* Go to popover > examples > hover.js
* Modify the example as follow:
```javascript
state = {
renderPopover: true
};
componentDidMount() {
setTimeout(() => {
this.setState({ renderPopover: false });
}, 4000);
}
```
* pass `delay={{ whenClosed: 5000 }}`, make sure the delaty of whenClosed > timeout set above
* Add the following:
```javascript
return this.state.renderPopover ? (
<Popover popover={popoverProps}>
<FlexView hAlignContent='center' style={{ width: 150, border: '1px solid #dedede', padding: 10 }}>Hover me!</FlexView>
</Popover>
) : <div>nope</div>;
```
* Run the application `npm run showroom`
* make sure the developertool is opened to see all the errors
* go to the popover component, and check if the error in the issue #727 is shown.
> Should be compatible with every …

#727: Popover: debounced events are not canceled when component unmounts (closes #727)

---

src/loading-spinner/LoadingSpinner.js
src/meter/Meter.js
src/tablo/plugins/columnsReorder/columnsReorderGrid.js
src/text-overflow/TextOverflow.js

Closes #784
- run `npm run lint` with `consistent-rule: 2`

#784: Be compatible with `consistent-return` eslint rule  (closes #784)

---

src/tablo/plugins/autosize/autosizeGrid.js

Closes #777
Add a `scrollToRow={0}` to the example:
- on master: tablo start with vertical scroll position > 0
- with this PR: tablo start with vertical sscroll position = 0

#777: Tablo: scroll to selected row not working correctly (closes #777)

---

showroom/components.json
src/index.js
src/modal/Modal.js
src/modal/ModalPortal.js
src/modal/README.md
src/modal/examples/withContext.js
src/modal/index.js
src/modal/modalWithContext.js
test/components/Modal.test.js

Closes #794
tested manually on gdsm using
```js
import { modalWithContext } from 'buildo-react-components/lib/modal';
import { intlShape } from 'react-intl';
import './modal.scss';
export default modalWithContext({ intl: intlShape });
```
and adding `@intlMethods` on a component rendered inside the modal

#794: add the ability to pass custom React context to Modal render tree (closes #794)

---

src/dropdown/dropdown.scss

Closes #724 
**test plan**
- Go to dropDown menu component
- Try to select one of the options in one of the dropDown menu
- Hover over the dropdown, the text color of the **SELECTED VALUE** should **NOT** be changed, as the attached gif:

#724: Dropdown: text color should not change on hover (closes #724)

---

src/dropdown/Dropdown.js
src/dropdown/README.md

Closes #796
- dropdown in showroom still works as expected (selected value is a string)
- adding `simpleValue={false}`, value will be passed to `onChange` as an object

#796: Dropdown should allow to pass simpleValue=false (closes #796)

---

src/meter/Meter.js
src/meter/examples/customLabels.js

Closes #753
* In the examples/default.js, change the passed properties to (remove ranges, and add baseFillingColor)
const meterProps = {
style: { marginBottom: 20 },
baseFillingColor: 'brown'
};
No errors should be shown in the console.
* If a warning message with "You should pass baseFillingColor, ranges are not fully filled"
In the example file of customLabel.js, make sure to add the "baseFillingColor" property to make the warning disappears. 
> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should …

#753: Meter: ranges should have a default value (closes #753)

---

src/async-status-indicator/AsyncStatusIndicator.js
src/async-status-indicator/index.js

Closes #817
* install locally the react-components to  alinityPro project to test. 
* In alinityPro project use the exported AsyncStatusIndicatorState in: 
src/app/components/Basic/AsyncStatusIndicator/AsyncStatusIndicator.js
export { AsyncStatusIndicatorState as SavingState } from 'buildo-react-components/lib/async-status-indicator';
* make sure the async status is still working.

#817: AsyncStatusIndicator should export `SavingState` model (closes #817)

---

src/dropdown/dropdown.scss

Closes #827
multi values centered:
multi values centered and well spaced when wrapping:
size "small":

#827: dropdown:`Select-multi-value-wrapper` should be vertically centered (closes #827)

---

src/tablo/API.md
src/tablo/README.md
src/tablo/Tablo.js

Closes #831
- table scrolls with touch events ✅ 
- tap on desired position in scrollbars lane trigger a scroll in the desired position (just a little bit slow) ✅ 
Things to be noticed:
- dragging scrollbar cause a scroll in the opposite direction of touch gesture 

#831: Add touchScrollEnabled prop to Tablo component (closes #831)

---

src/dropdown/dropdown.scss

Closes #830
* In IE11, test the default size dropdown:
* Add more options till they wrap to next line:
*Change the size of the dropdown in the multi example by adding the property `size='small'`, in IE11
*Continue adding options till they wrapped to  new line:
* Add the property searchable to dropdown and test the dropdown
Repeat the steps above in Chrome, and make sure everything is working.
> An example of partial test is a field displaying 4 possible values. If 3 values …

#830: Dropdown: on IE11, values in multi-select mode are not vertically aligned when in single line (closes #830)

---

src/tablo/plugins/columnsResize/columnsResizeGrid.js

Closes #842
tested on QIA about this issue: https://github.omnilab.our.buildo.io/buildo/aliniq/issues/5114
- pass onColumnResize -> resize enabled and working, tcomb doesn't complain ✅ 
- pass `onColumnResize: undefined` -> resize disable, tcomb doesn't complain ✅ 

#842: Tablo: resizing plugin should be disabled if onColumnsResize is missing (closes #842)

---

src/tablo/plugins/columnsResize/columnsResizeGrid.js

Closes #844
this commit was meant to be pushed on #843 , the test plan is the same

#844: Tablo: never pass onColumnResize down directly (closes #844)

---

src/dropdown/Dropdown.js

Closes #848
- `npm start`
- pass the new props to a dropdown
- no tcomb error in console
- the three cb work correctly

#848: add `onInputChange`, `onBlur` and `onFocus` to Dropdown proptypes (closes #848)

---

src/tablo/Cell/Cell.js

Closes #852
- Firefox
- Safari
- Google Chrome
- IE

#852: Tablo: cell content is not vertically centered in Safari (closes #852)

---

src/dropdown/dropdown.scss

Closes #850
- when focused hitting TAB
- when disabled, border doesn't change on focus

#850: Dropdown: no style for focus (closes #850)

---

src/tablo/plugins/columnsReorder/columnsReorderGrid.js

Closes #862
- short form with no children
- only one column

#862: Tablo throws when there are less then 2 children (closes #862)

---

src/DropdownMenu/menu.scss

Closes #836
Now the `.menu-item` takes the whole `.menu-row` height making the entire area clickable.

#836: PanelMenu: clicking near a menu item may close the menu without calling the item's action (closes #836)

---

src/dropdown/Dropdown.js
src/dropdown/examples/groups.js

Closes #880
- groups are preserving their order and are not sorted alphabetically
- the original order is preserved inside groups
- non-grouped options are on top (with no group header and preserving their order)
- it works fine even using arrow keys
- non-grouped dropdown works fine

#880: Dropdown: option groups should preserve the order in which they appear (closes #880)

---

src/dropdown/Dropdown.js
src/dropdown/index.js

Closes #891
- dropdown menu is still rendered as expected
- we can import and use `defaultMenuRenderer` from outside (tested on GDSM)

#891: Dropdown: export defaultMenuRenderer (closes #891)

---

src/focusable-view/FocusableView.d.ts
src/focusable-view/index.d.ts

Closes #923
tested on AlinityPRO:
- `FocusableView` is typed
- `focusable-view/FocusableView` exports both the component and `FocusableViewProps`

#923: [typescript .d.ts] FocusableView (closes #923)

---

src/utils/index.js

Closes #996
- tested on alinity-pro ✅ 

#996: Missing default for contextTypes in getContextWrapper util (closes #996)

---

src/Tablo/tablo.scss

#1002: Tablo: border row should be applied to inner cells  (closes #1002)

---

src/Popover/Popover.js

To resolve this [issue](https://github.omnilab.our.buildo.io/buildo/alinity-pro/issues/6049) I came up with this solution.
Removing the `saveValuesFromNodeTree` in `componentWillReceiveProps` seems to have no cons.
Since you have more domain knowledge can you give me your feedback on this?
Thansk

Popover anchor and re render

---

src/Dropdown/Dropdown.d.ts

Closes #1014
tested in this branch https://github.omnilab.our.buildo.io/buildo/alinity-pro/tree/typo-dropdown
(see especially last commit.. still slightly broken, but usable after these fixes)
> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and …

#1014: Dropdown typings for `optionRenderer` and `optionGroupRenderer` are slightly broken (closes #1014)

---

src/ScrollView/ScrollView.js
src/ScrollView/scrollView.scss

Closes #1029
tested on AlinityPRO:
- scrollbars work as before
- they're no longer visible/hoverable when thumb has height/width `0`
- if `children` use `PureComponent` (as we're doing) no useless render
- tested on `UserPreferences` page: same number of renders for `UserRow`

#1029: ScrollView: scrollbars are visible even when thumb is hidden (closes #1029)

---

src/Dropdown/Dropdown.tsx

Closes #1133
tested with examples:
returns `null` when you manually remove the last value

#1133: Dropdown: clearing returns `null` to `onChange` when `multi = true` (closes #1133)

---

src/Button/Button.tsx
src/Icon/Icon.tsx
test/components/Icon.test.tsx

Added a simple test for the new `Icon.prefix` prop
Would be nice to have `Button.iconPrefix` usable only in case of `Button.icon`.. This was the quickest solution for the moment

Allow custom prefixes for icons (in Icon and Button) (closes #1150)

---

src/Popover/Popover.tsx
src/utils/index.ts

Closes #1164
example with `attachToBody` works both on React16 and React15

#1164: Popover does not work on React16 when attached to body (closes #1164)

---

package.json
src/FocusableView/FocusableView.tsx
src/Tablo/Column/columnUtility.ts
src/Tablo/plugins/columnsReorder/htmlBackend.ts
src/Tablo/plugins/columnsResize/columnsResizeGrid.tsx
src/Tablo/utils.ts
src/TextOverflow/TextOverflow.tsx
typings/css-element-queries.d.ts

Closes #1170
`test` `build` and `start` look 👍 
some more context on the `TS4023` error: https://github.com/Microsoft/TypeScript/issues/5711
and on the "Arbitrary expression.." one: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#arbitrary-expressions-are-forbidden-in-export-assignments-in-ambient-contexts
> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has …

#1170: upgrade typescript version to 2.6.2 (closes #1170)

---

src/FormattedText/Examples.md
src/FormattedText/FormattedText.tsx

Closes #1179
[![https://gyazo.com/ac490dcefb15c1c8c512c445103ecce3](https://i.gyazo.com/ac490dcefb15c1c8c512c445103ecce3.gif)](https://gyazo.com/ac490dcefb15c1c8c512c445103ecce3)

#1179: FormattedText: there is no way to disable linkify feature (closes #1179)

---

src/FormField/InputField.tsx
src/FormField/PasswordInputField.tsx
src/FormField/TextareaField.tsx

Closes #1294
- VSCode now shows the `label` prop as `JSX.Element | string`
- `<InputField label={<View />} />` => no errors for the `label` prop

#1294: Can't pass a React Element as label for InputField (closes #1294)

---

src/TimePicker/TimePicker.tsx

Closes #1329
when running styleguidist, `Timepicker` name displays correctly:

#1329: bring back Timepicker in showroom (closes #1329)

---

src/DatePicker/DatePicker.tsx
src/DatePicker/Examples.md
src/FormField/DatePickerField.tsx

Closes #1347
Example in showroom still works as expected

#1347: Remove returnFormat prop from DatePicker (closes #1347)

---

src/Form/Form.tsx

Closes #1387
Tested in preview:
* `noSubmitOnEnter` actually disables submit on enter
* Submit button still works, since handled outside the scope of `Form`

#1387: Allow to disable submit on enter in Form (closes #1387)

---

src/FormField/FormField.tsx
src/FormattedText/FormattedText.tsx

Closes #1405
No more warning for `FormField`:
No more warning for `FormattedText` too:

#1405: React missing unique key warning in FormField (closes #1405)

---

src/Dropdown/Examples.md
src/Dropdown/MultiDropdownWithSelectAll.tsx

Closes #1410
New example added.
Tested:
- the `All` option is already visible before the user starts typing
- It's possible to type a search string even when the `All` option is selected
- The input doesn't lose focus when the options are loaded

#1410: MultiDropdownWithSelectAll defects when options are loaded async (closes #1410)

---

src/FormField/CheckboxField.tsx
src/FormField/DatePickerField.tsx
src/FormField/InputField.tsx
src/FormField/MultiDropdownField.tsx
src/FormField/PasswordInputField.tsx
src/FormField/RadioGroupField.tsx
src/FormField/SingleDropdownField.tsx
src/FormField/TextareaField.tsx
src/FormField/TimePickerField.tsx
src/FormField/ToggleField.tsx

Closes #1427
All the components in the FormField module now have a mandatory property requiring an object containing all the properties of their inner component. This object has the same type of the `Props` of the inner component.
No change in the UX has been introduced

#1427: FormField components should have a prop packing all inner component's props instead of spreading them (closes #1427)

---

src/Menu/Examples.md
src/Menu/Menu.tsx

Closes #1436
The horizontal alignment of the Menu is customizable using the `anchor` prop.
Position is "bottom" and anchor is "end" by default, to avoid introduce breaking changes. This also fixes an error in the examples.
`anchor="start"`           |  `anchor="end"` or not defined
:-------------------------:|:-------------------------:

#1436: Add parameter to customize anchor of Menu component (closes #1436)

---

.smooth-releaserc
CHANGELOG.md
package.json

Closes #1441
I manually generated all the missing changelogs running `smooth-release --changelog --gh-release-all` and updated `.smooth-releaserc` to generate the changelog with any future release

#1441: CHANGELOG is out of date (closes #1441)

---

src/Button/StatefulButton.tsx
src/DateField/DateField.tsx
src/DatePicker/DatePicker.tsx
src/Input/ConfirmationInput.tsx
src/Popover/Popover.tsx
src/Tablo/plugins/scrollable/scrollableGrid.tsx
src/TextOverflow/TextOverflow.tsx
src/Toaster/Toaster.tsx
src/Toggle/Toggle.tsx

Closes #1435
[as suggested](https://github.com/buildo/react-components/issues/1435#issuecomment-615166577) I replaced all the usages of deprecated `componentWillReceiveProps` with `componentDidUpdate`.
Looking at the code seems like nothing should change, but I'm not sure about how we should test this.
Showroom works correctly and `yarn test` detects no issue.
Several warnings about `componentWillReceiveProps` being renamed will still be displayed due to dependencies.

#1435: componentWillReceiveProps has been renamed

---

src/DatePicker/datePicker.scss

Closes #1409
remove both the horizontal and vertical empty space and also remove the double border

#1409: DatePicker has 1px left border on open calendar
